import type { Alert, KpiCard as Kpi } from '@hydro/shared-types';
import { formatQuantity } from '@hydro/units';
import { StatusPill, type StatusKind } from './ui';

const GROUP_LABELS: Record<Kpi['group'], string> = {
  hydrology: 'Hydrology',
  drought: 'Drought',
  flood: 'Flood',
  water_quality: 'Water quality',
  supply: 'Water supply',
  demand: 'Water demand',
};

const ACCENT: Record<Kpi['status'], string> = {
  normal: 'before:bg-emerald-500',
  watch: 'before:bg-amber-500',
  warning: 'before:bg-orange-500',
  critical: 'before:bg-red-500',
  unknown: 'before:bg-ink-300',
};

export function KpiTile({ kpi }: { kpi: Kpi }) {
  const value = formatQuantity(kpi.value, kpi.unit, { precision: kpi.precision, hideUnit: true });
  const unit = kpi.unit === 'dimensionless' ? '' : kpi.unit === 'm3/s' ? 'm³/s' : kpi.unit === 'degC' ? '°C' : kpi.unit;

  return (
    <div
      className={`relative overflow-hidden rounded-lg border border-ink-200 bg-white p-3 shadow-card before:absolute before:inset-y-0 before:left-0 before:w-1 ${ACCENT[kpi.status]}`}
    >
      <div className="flex items-start justify-between gap-2 pl-1.5">
        <p className="text-2xs font-medium uppercase tracking-wide text-ink-500">{kpi.label}</p>
        {kpi.status !== 'normal' && (
          <StatusPill status={kpi.status as StatusKind} dot={false}>
            {kpi.status}
          </StatusPill>
        )}
      </div>
      <p className="mt-1 flex items-baseline gap-1 pl-1.5">
        <span className="text-2xl font-semibold tabular tracking-tight text-ink-900">{value}</span>
        {unit && <span className="text-xs font-medium text-ink-500">{unit}</span>}
      </p>
      {kpi.delta !== null && kpi.deltaLabel && (
        <p className="mt-0.5 pl-1.5 text-2xs">
          <span className={kpi.delta >= 0 ? 'text-emerald-700' : 'text-orange-700'}>
            {kpi.delta >= 0 ? '▲' : '▼'} {Math.abs(kpi.delta).toFixed(kpi.delta >= 100 ? 0 : 1)}%
          </span>{' '}
          <span className="text-ink-500">{kpi.deltaLabel}</span>
        </p>
      )}
      <p className="mt-1.5 pl-1.5 text-2xs leading-snug text-ink-500">{kpi.context}</p>
    </div>
  );
}

export function KpiGroup({ group, kpis }: { group: Kpi['group']; kpis: Kpi[] }) {
  if (kpis.length === 0) return null;
  return (
    <section>
      <h2 className="mb-2 text-xs font-semibold uppercase tracking-wide text-ink-500">{GROUP_LABELS[group]}</h2>
      <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-4">
        {kpis.map((k) => (
          <KpiTile key={k.id} kpi={k} />
        ))}
      </div>
    </section>
  );
}

const ALERT_STATUS: Record<Alert['severity'], StatusKind> = {
  info: 'info',
  watch: 'watch',
  warning: 'warning',
  critical: 'critical',
};

export function AlertList({ alerts }: { alerts: Alert[] }) {
  if (alerts.length === 0) {
    return (
      <p className="text-xs text-ink-500">
        No alerts. Rules are evaluated on every dashboard request against the current record; an empty list means no
        threshold was crossed, not that nothing was checked.
      </p>
    );
  }
  return (
    <ul className="space-y-2">
      {alerts.map((a) => (
        <li key={a.id} className="rounded-md border border-ink-200 bg-white p-3">
          <div className="flex flex-wrap items-center gap-2">
            <StatusPill status={ALERT_STATUS[a.severity]}>{a.severity}</StatusPill>
            <span className="text-2xs uppercase tracking-wide text-ink-400">{a.category.replace('_', ' ')}</span>
            <span className="ml-auto text-2xs text-ink-400">{new Date(a.issuedAt).toLocaleString()}</span>
          </div>
          <p className="mt-1.5 text-sm font-medium text-ink-900">{a.title}</p>
          <p className="mt-1 text-xs leading-relaxed text-ink-600">{a.body}</p>
          <p className="mt-1.5 text-2xs text-ink-400">
            Generated by {a.generatedBy === 'rule' ? 'a threshold rule' : 'the Copilot'} · evidence: {a.evidence.join(', ')}
          </p>
        </li>
      ))}
    </ul>
  );
}
