import type { ReactNode } from 'react';
import { useApp } from '@/stores/app';

// ---------------------------------------------------------------------------
// Layout primitives
// ---------------------------------------------------------------------------

export function Card({
  title,
  subtitle,
  actions,
  children,
  className = '',
  bodyClassName = 'p-4',
}: {
  title?: ReactNode;
  subtitle?: ReactNode;
  actions?: ReactNode;
  children: ReactNode;
  className?: string;
  bodyClassName?: string;
}) {
  return (
    <section className={`card ${className}`}>
      {(title || actions) && (
        <header className="card-header">
          <div className="min-w-0">
            {title && <h3 className="card-title">{title}</h3>}
            {subtitle && <p className="card-subtitle">{subtitle}</p>}
          </div>
          {actions && <div className="flex shrink-0 items-center gap-2">{actions}</div>}
        </header>
      )}
      <div className={bodyClassName}>{children}</div>
    </section>
  );
}

export function PageHeader({
  title,
  description,
  actions,
}: {
  title: string;
  description?: string;
  actions?: ReactNode;
}) {
  return (
    <div className="mb-5 flex flex-wrap items-start justify-between gap-3">
      <div className="min-w-0">
        <h1 className="text-xl font-semibold tracking-tight text-ink-900">{title}</h1>
        {description && <p className="mt-1 max-w-3xl text-sm text-ink-600">{description}</p>}
      </div>
      {actions && <div className="flex shrink-0 flex-wrap items-center gap-2">{actions}</div>}
    </div>
  );
}

export function Grid({ children, cols = 2 }: { children: ReactNode; cols?: 1 | 2 | 3 | 4 }) {
  const map = { 1: '', 2: 'lg:grid-cols-2', 3: 'md:grid-cols-2 xl:grid-cols-3', 4: 'sm:grid-cols-2 xl:grid-cols-4' };
  return <div className={`grid grid-cols-1 gap-4 ${map[cols]}`}>{children}</div>;
}

// ---------------------------------------------------------------------------
// Status
// ---------------------------------------------------------------------------

export type StatusKind = 'normal' | 'watch' | 'warning' | 'critical' | 'unknown' | 'info' | 'success';

const STATUS_STYLES: Record<StatusKind, string> = {
  normal: 'border-emerald-200 bg-emerald-50 text-emerald-800',
  success: 'border-emerald-200 bg-emerald-50 text-emerald-800',
  watch: 'border-amber-200 bg-amber-50 text-amber-800',
  warning: 'border-orange-200 bg-orange-50 text-orange-800',
  critical: 'border-red-200 bg-red-50 text-red-800',
  unknown: 'border-ink-200 bg-ink-50 text-ink-600',
  info: 'border-hydro-200 bg-hydro-50 text-hydro-800',
};

const STATUS_DOT: Record<StatusKind, string> = {
  normal: 'bg-emerald-500',
  success: 'bg-emerald-500',
  watch: 'bg-amber-500',
  warning: 'bg-orange-500',
  critical: 'bg-red-500',
  unknown: 'bg-ink-400',
  info: 'bg-hydro-500',
};

export function StatusPill({ status, children, dot = true }: { status: StatusKind; children: ReactNode; dot?: boolean }) {
  return (
    <span className={`chip ${STATUS_STYLES[status]}`}>
      {dot && <span className={`h-1.5 w-1.5 rounded-full ${STATUS_DOT[status]}`} aria-hidden />}
      {children}
    </span>
  );
}

export function SyntheticBadge({ compact = false }: { compact?: boolean }) {
  return (
    <span
      className="chip border-violet-200 bg-violet-50 text-violet-800"
      title="Every value shown derives from a synthetic demonstration dataset generated by a conceptual rainfall-runoff model. No value is an observation."
    >
      <span className="h-1.5 w-1.5 rounded-full bg-violet-500" aria-hidden />
      {compact ? 'Synthetic' : 'Synthetic demonstration data'}
    </span>
  );
}

// ---------------------------------------------------------------------------
// States
// ---------------------------------------------------------------------------

export function Skeleton({ className = 'h-4 w-full' }: { className?: string }) {
  return <div className={`skeleton ${className}`} aria-hidden />;
}

export function LoadingPanel({ label = 'Computing…', lines = 4 }: { label?: string; lines?: number }) {
  return (
    <div className="space-y-3 p-4" role="status" aria-live="polite">
      <div className="flex items-center gap-2 text-xs text-ink-500">
        <Spinner />
        {label}
      </div>
      {Array.from({ length: lines }).map((_, i) => (
        <Skeleton key={i} className={`h-3 ${i % 3 === 0 ? 'w-5/6' : i % 3 === 1 ? 'w-full' : 'w-2/3'}`} />
      ))}
    </div>
  );
}

export function Spinner({ className = 'h-3.5 w-3.5' }: { className?: string }) {
  return (
    <svg className={`${className} animate-spin text-hydro-600`} viewBox="0 0 24 24" fill="none" aria-hidden>
      <circle className="opacity-20" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="3" />
      <path className="opacity-90" fill="currentColor" d="M4 12a8 8 0 018-8v3a5 5 0 00-5 5H4z" />
    </svg>
  );
}

export function EmptyState({ title, body, action }: { title: string; body?: string; action?: ReactNode }) {
  return (
    <div className="flex flex-col items-center justify-center gap-2 rounded-lg border border-dashed border-ink-200 bg-ink-50/60 px-6 py-10 text-center">
      <p className="text-sm font-medium text-ink-700">{title}</p>
      {body && <p className="max-w-md text-xs text-ink-500">{body}</p>}
      {action}
    </div>
  );
}

export function ErrorState({ error, retry }: { error: unknown; retry?: () => void }) {
  const message = error instanceof Error ? error.message : String(error);
  return (
    <div className="rounded-lg border border-red-200 bg-red-50 px-4 py-3">
      <p className="text-sm font-semibold text-red-900">This analysis could not be completed</p>
      <p className="mt-1 text-xs text-red-800">{message}</p>
      {retry && (
        <button type="button" className="btn btn-secondary mt-3" onClick={retry}>
          Try again
        </button>
      )}
    </div>
  );
}

export function InsufficientData({ message }: { message: string }) {
  return (
    <div className="rounded-lg border border-amber-200 bg-amber-50 px-4 py-3">
      <p className="text-sm font-semibold text-amber-900">Insufficient data</p>
      <p className="mt-1 text-xs text-amber-800">{message}</p>
    </div>
  );
}

export function WarningList({ warnings, title = 'Cautions' }: { warnings: string[]; title?: string }) {
  if (warnings.length === 0) return null;
  return (
    <div className="rounded-md border border-amber-200 bg-amber-50 px-3 py-2">
      <p className="text-2xs font-semibold uppercase tracking-wide text-amber-900">{title}</p>
      <ul className="mt-1 space-y-1">
        {warnings.map((w, i) => (
          <li key={i} className="text-xs leading-relaxed text-amber-900">
            {w}
          </li>
        ))}
      </ul>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Metric display
// ---------------------------------------------------------------------------

export function Metric({
  label,
  value,
  unit,
  hint,
  status,
}: {
  label: string;
  value: ReactNode;
  unit?: string;
  hint?: string;
  status?: StatusKind;
}) {
  return (
    <div className="rounded-md border border-ink-200 bg-white px-3 py-2">
      <p className="text-2xs font-medium uppercase tracking-wide text-ink-500">{label}</p>
      <p className="mt-0.5 flex items-baseline gap-1">
        <span className={`text-lg font-semibold tabular ${status === 'critical' ? 'text-red-700' : 'text-ink-900'}`}>{value}</span>
        {unit && <span className="text-xs text-ink-500">{unit}</span>}
      </p>
      {hint && <p className="mt-0.5 text-2xs leading-snug text-ink-500">{hint}</p>}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Tabs
// ---------------------------------------------------------------------------

export function Tabs<T extends string>({
  tabs,
  active,
  onChange,
}: {
  tabs: { id: T; label: string; count?: number }[];
  active: T;
  onChange: (id: T) => void;
}) {
  return (
    <div className="flex flex-wrap gap-1 border-b border-ink-200" role="tablist">
      {tabs.map((t) => (
        <button
          key={t.id}
          role="tab"
          aria-selected={active === t.id}
          type="button"
          onClick={() => onChange(t.id)}
          className={`-mb-px border-b-2 px-3 py-2 text-xs font-medium transition-colors ${
            active === t.id ? 'border-hydro-600 text-hydro-800' : 'border-transparent text-ink-500 hover:text-ink-800'
          }`}
        >
          {t.label}
          {t.count !== undefined && <span className="ml-1.5 rounded bg-ink-100 px-1 text-2xs text-ink-600">{t.count}</span>}
        </button>
      ))}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Toasts
// ---------------------------------------------------------------------------

export function Toasts() {
  const { toasts, dismissToast } = useApp();
  if (toasts.length === 0) return null;
  return (
    <div className="pointer-events-none fixed bottom-4 right-4 z-50 flex w-80 flex-col gap-2">
      {toasts.map((t) => (
        <div
          key={t.id}
          className={`pointer-events-auto animate-fade-in rounded-lg border px-3 py-2 shadow-panel ${STATUS_STYLES[
            t.kind === 'error' ? 'critical' : t.kind === 'success' ? 'normal' : t.kind === 'warning' ? 'warning' : 'info'
          ]}`}
          role="status"
        >
          <div className="flex items-start justify-between gap-2">
            <p className="text-xs font-semibold">{t.title}</p>
            <button type="button" className="text-xs opacity-60 hover:opacity-100" onClick={() => dismissToast(t.id)} aria-label="Dismiss">
              ✕
            </button>
          </div>
          {t.body && <p className="mt-1 text-2xs leading-relaxed">{t.body}</p>}
        </div>
      ))}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Misc
// ---------------------------------------------------------------------------

export function ComingSoon({ feature, requirement }: { feature: string; requirement?: string }) {
  return (
    <div className="rounded-lg border border-dashed border-hydro-300 bg-hydro-50/60 px-4 py-3">
      <p className="text-sm font-semibold text-hydro-900">
        {requirement ? 'Integration required' : 'Coming soon'}: {feature}
      </p>
      {requirement && <p className="mt-1 text-xs text-hydro-800">{requirement}</p>}
    </div>
  );
}

export function DefinitionList({ items }: { items: { term: string; description: ReactNode }[] }) {
  return (
    <dl className="divide-y divide-ink-100">
      {items.map((it, i) => (
        <div key={i} className="grid grid-cols-1 gap-1 py-2 sm:grid-cols-3">
          <dt className="text-2xs font-semibold uppercase tracking-wide text-ink-500">{it.term}</dt>
          <dd className="text-xs leading-relaxed text-ink-800 sm:col-span-2">{it.description}</dd>
        </div>
      ))}
    </dl>
  );
}
