/**
 * Potomac Demonstration Watershed — SYNTHETIC data.
 *
 * ────────────────────────────────────────────────────────────────────────────
 * THIS IS NOT REAL DATA. Nothing in this module is an observation.
 *
 * The series are produced by a deterministic conceptual rainfall-runoff model
 * (stochastic precipitation generator → soil-moisture store → two linear
 * reservoirs) with a seasonal climate signal and a multi-year wet/dry
 * oscillation. The catchment is loosely styled on the Potomac River basin
 * above Point of Rocks so that magnitudes are plausible, but no value
 * corresponds to any gauge reading, and the geometry is a generated shape,
 * not a delineated watershed boundary.
 *
 * It exists so that every analytical capability of the platform can be
 * exercised immediately after installation without external credentials.
 * Every record it produces is flagged `is_synthetic` and every provenance
 * record built from it says so.
 * ────────────────────────────────────────────────────────────────────────────
 */

import { hargreavesPet } from '@hydro/hydrology-core';

export const DEMO_DISCLAIMER =
  'Synthetic demonstration data generated by a conceptual rainfall-runoff model. Not observed data. Not suitable for any operational, design or regulatory purpose.';

export const DEMO_IDS = {
  user: '00000000-0000-4000-8000-000000000001',
  project: '00000000-0000-4000-8000-000000000010',
  watershed: '00000000-0000-4000-8000-000000000020',
  reservoir: '00000000-0000-4000-8000-000000000030',
} as const;

function rng(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function uuid(n: number): string {
  const hex = n.toString(16).padStart(12, '0');
  return `00000000-0000-4000-8000-${hex}`;
}

export interface DemoSubbasin {
  id: string;
  name: string;
  areaKm2: number;
  meanElevationM: number;
  meanSlopePct: number;
  curveNumber: number;
  dominantLandCover: string;
  centroid: { lon: number; lat: number };
  polygon: [number, number][];
}

export interface DemoStation {
  id: string;
  code: string;
  name: string;
  type: 'streamgage' | 'precipitation' | 'weather' | 'water_quality' | 'groundwater' | 'reservoir';
  lon: number;
  lat: number;
  elevationM: number;
  drainageAreaKm2: number | null;
  subbasinId: string | null;
  operator: string;
}

export interface DemoDaily {
  dates: string[];
  precipMm: number[];
  tmaxC: number[];
  tminC: number[];
  tmeanC: number[];
  petMm: number[];
  aetMm: number[];
  soilMoistureMm: number[];
  dischargeM3s: number[];
  stageM: number[];
  /** Per-streamgage discharge, keyed by station code. */
  byGage: Record<string, number[]>;
}

export interface DemoWaterQuality {
  t: string;
  stationCode: string;
  parameter: string;
  value: number;
  unit: string;
}

export interface DemoReservoirStep {
  t: string;
  storageMcm: number;
  elevationM: number;
  inflowM3s: number;
  releaseM3s: number;
  spillM3s: number;
  evaporationMcm: number;
}

export interface DemoDemand {
  t: string;
  sector: 'municipal' | 'agricultural' | 'industrial';
  demandMcm: number;
  population: number;
}

export interface DemoDataset {
  watershed: {
    id: string;
    name: string;
    huc: string;
    areaKm2: number;
    description: string;
    outlet: { lon: number; lat: number };
    polygon: [number, number][];
    centroid: { lon: number; lat: number };
    bbox: { minLon: number; minLat: number; maxLon: number; maxLat: number };
  };
  subbasins: DemoSubbasin[];
  stations: DemoStation[];
  reaches: { id: string; name: string; streamOrder: number; lengthKm: number; line: [number, number][] }[];
  daily: DemoDaily;
  waterQuality: DemoWaterQuality[];
  reservoir: {
    id: string;
    name: string;
    lon: number;
    lat: number;
    capacityMcm: number;
    deadStorageMcm: number;
    conservationPoolMcm: number;
    floodPoolMcm: number;
    purpose: string[];
    monthly: DemoReservoirStep[];
  };
  demand: DemoDemand[];
  groundwater: { t: string; depthToWaterM: number }[];
  generatedAt: string;
  disclaimer: string;
}

const CENTER = { lon: -77.62, lat: 39.28 };
const AREA_KM2 = 24_996; // plausible order of magnitude for the upper Potomac
const LATITUDE = 39.28;

/** Generate a closed, jittered polygon around a centre. */
function blob(center: { lon: number; lat: number }, radiusDeg: number, seed: number, n = 48): [number, number][] {
  const r = rng(seed);
  const pts: [number, number][] = [];
  const wobble = Array.from({ length: 5 }, () => r() * 2 - 1);
  for (let i = 0; i < n; i++) {
    const a = (2 * Math.PI * i) / n;
    let rad = radiusDeg;
    wobble.forEach((w, k) => {
      rad *= 1 + 0.11 * w * Math.sin((k + 2) * a + k);
    });
    pts.push([
      Number((center.lon + rad * Math.cos(a) * 1.32).toFixed(5)),
      Number((center.lat + rad * Math.sin(a) * 0.78).toFixed(5)),
    ]);
  }
  pts.push(pts[0]);
  return pts;
}

const SUBBASIN_SPECS: { name: string; frac: number; elev: number; slope: number; cn: number; cover: string; dx: number; dy: number }[] = [
  { name: 'North Branch', frac: 0.19, elev: 620, slope: 14.2, cn: 71, cover: 'Deciduous forest', dx: -0.95, dy: 0.42 },
  { name: 'South Branch', frac: 0.22, elev: 545, slope: 12.8, cn: 73, cover: 'Deciduous forest', dx: -0.72, dy: -0.46 },
  { name: 'Cacapon Valley', frac: 0.14, elev: 410, slope: 9.4, cn: 76, cover: 'Mixed forest / pasture', dx: -0.16, dy: -0.34 },
  { name: 'Conococheague', frac: 0.16, elev: 305, slope: 6.1, cn: 79, cover: 'Cultivated cropland', dx: 0.21, dy: 0.44 },
  { name: 'Antietam', frac: 0.12, elev: 260, slope: 5.3, cn: 81, cover: 'Cultivated cropland', dx: 0.52, dy: 0.12 },
  { name: 'Monocacy', frac: 0.17, elev: 215, slope: 4.6, cn: 80, cover: 'Cropland / developed', dx: 0.78, dy: -0.22 },
];

export function buildDemoWatershed(years = 30, seed = 20260901): DemoDataset {
  const subbasins: DemoSubbasin[] = SUBBASIN_SPECS.map((s, i) => {
    const centroid = { lon: CENTER.lon + s.dx, lat: CENTER.lat + s.dy };
    return {
      id: uuid(200 + i),
      name: s.name,
      areaKm2: Number((AREA_KM2 * s.frac).toFixed(1)),
      meanElevationM: s.elev,
      meanSlopePct: s.slope,
      curveNumber: s.cn,
      dominantLandCover: s.cover,
      centroid,
      polygon: blob(centroid, 0.24 + s.frac * 0.7, seed + i * 17),
    };
  });

  const outlet = { lon: -77.5433, lat: 39.2735 };

  const stations: DemoStation[] = [
    { id: uuid(300), code: 'DEMO-01638500', name: 'Potomac River at Point of Rocks (demo)', type: 'streamgage', lon: -77.5433, lat: 39.2735, elevationM: 61, drainageAreaKm2: 24996, subbasinId: null, operator: 'Synthetic demo network' },
    { id: uuid(301), code: 'DEMO-01619500', name: 'Antietam Creek near Sharpsburg (demo)', type: 'streamgage', lon: -77.7285, lat: 39.4266, elevationM: 88, drainageAreaKm2: 2999, subbasinId: uuid(204), operator: 'Synthetic demo network' },
    { id: uuid(302), code: 'DEMO-01643000', name: 'Monocacy River at Jug Bridge (demo)', type: 'streamgage', lon: -77.3689, lat: 39.3937, elevationM: 66, drainageAreaKm2: 4249, subbasinId: uuid(205), operator: 'Synthetic demo network' },
    { id: uuid(310), code: 'DEMO-PCP-NB', name: 'North Branch precipitation (demo)', type: 'precipitation', lon: -78.57, lat: 39.70, elevationM: 640, drainageAreaKm2: null, subbasinId: uuid(200), operator: 'Synthetic demo network' },
    { id: uuid(311), code: 'DEMO-PCP-SB', name: 'South Branch precipitation (demo)', type: 'precipitation', lon: -78.34, lat: 38.82, elevationM: 512, drainageAreaKm2: null, subbasinId: uuid(201), operator: 'Synthetic demo network' },
    { id: uuid(312), code: 'DEMO-PCP-MO', name: 'Monocacy precipitation (demo)', type: 'precipitation', lon: -76.84, lat: 39.06, elevationM: 198, drainageAreaKm2: null, subbasinId: uuid(205), operator: 'Synthetic demo network' },
    { id: uuid(320), code: 'DEMO-WX-HGR', name: 'Hagerstown climate station (demo)', type: 'weather', lon: -77.72, lat: 39.64, elevationM: 214, drainageAreaKm2: null, subbasinId: uuid(203), operator: 'Synthetic demo network' },
    { id: uuid(330), code: 'DEMO-WQ-POR', name: 'Point of Rocks water quality (demo)', type: 'water_quality', lon: -77.5439, lat: 39.2740, elevationM: 61, drainageAreaKm2: null, subbasinId: null, operator: 'Synthetic demo network' },
    { id: uuid(331), code: 'DEMO-WQ-ANT', name: 'Antietam Creek water quality (demo)', type: 'water_quality', lon: -77.7290, lat: 39.4270, elevationM: 88, drainageAreaKm2: null, subbasinId: uuid(204), operator: 'Synthetic demo network' },
    { id: uuid(332), code: 'DEMO-WQ-MON', name: 'Monocacy River water quality (demo)', type: 'water_quality', lon: -77.3695, lat: 39.3940, elevationM: 66, drainageAreaKm2: null, subbasinId: uuid(205), operator: 'Synthetic demo network' },
    { id: uuid(340), code: 'DEMO-GW-01', name: 'Frederick Valley observation well (demo)', type: 'groundwater', lon: -77.41, lat: 39.41, elevationM: 92, drainageAreaKm2: null, subbasinId: uuid(205), operator: 'Synthetic demo network' },
  ];

  const daily = generateDaily(years, seed);
  const waterQuality = generateWaterQuality(daily, seed + 991);
  const reservoir = generateReservoir(daily, seed + 1771);
  const demand = generateDemand(daily, seed + 4231);
  const groundwater = generateGroundwater(daily, seed + 6113);

  const polygon = blob(CENTER, 1.15, seed);
  const lons = polygon.map((p) => p[0]);
  const lats = polygon.map((p) => p[1]);

  return {
    watershed: {
      id: DEMO_IDS.watershed,
      name: 'Potomac Demonstration Watershed',
      huc: '02070004 (illustrative)',
      areaKm2: AREA_KM2,
      description:
        'Synthetic demonstration catchment loosely styled on the Potomac River basin above Point of Rocks. ' +
        'Geometry is generated, not delineated. All time series are model output, not observations.',
      outlet,
      polygon,
      centroid: CENTER,
      bbox: { minLon: Math.min(...lons), minLat: Math.min(...lats), maxLon: Math.max(...lons), maxLat: Math.max(...lats) },
    },
    subbasins,
    stations,
    reaches: buildReaches(subbasins, outlet),
    daily,
    waterQuality,
    reservoir,
    demand,
    groundwater,
    generatedAt: new Date().toISOString(),
    disclaimer: DEMO_DISCLAIMER,
  };
}

function buildReaches(subbasins: DemoSubbasin[], outlet: { lon: number; lat: number }) {
  const mainstem: [number, number][] = [
    [-78.9, 39.62], [-78.4, 39.55], [-78.0, 39.6], [-77.9, 39.45], [-77.75, 39.42],
    [-77.72, 39.3], [-77.6, 39.28], [outlet.lon, outlet.lat],
  ];
  const reaches = [
    { id: uuid(400), name: 'Potomac mainstem (demo)', streamOrder: 6, lengthKm: 268, line: mainstem },
  ];
  subbasins.forEach((s, i) => {
    reaches.push({
      id: uuid(401 + i),
      name: `${s.name} tributary (demo)`,
      streamOrder: 4,
      lengthKm: Number((40 + s.areaKm2 / 90).toFixed(1)),
      line: [
        [s.centroid.lon, s.centroid.lat],
        [(s.centroid.lon + outlet.lon) / 2, (s.centroid.lat + outlet.lat) / 2],
        [outlet.lon, outlet.lat],
      ] as [number, number][],
    });
  });
  return reaches;
}

/**
 * Conceptual daily model:
 *   1. Precipitation occurrence (Bernoulli, seasonally varying) then depth
 *      (exponential) — a standard weather generator.
 *   2. Temperature from a seasonal harmonic plus noise; PET by Hargreaves.
 *   3. Soil-moisture store with AET proportional to storage; runoff
 *      coefficient increasing with wetness (a saturation-excess analogue).
 *   4. Two linear reservoirs, quick and slow, routed to the outlet.
 */
function generateDaily(years: number, seed: number): DemoDaily {
  const r = rng(seed);
  const end = new Date(Date.UTC(2026, 8, 1)); // 2026-09-01
  const start = new Date(end.getTime() - years * 365.25 * 86400000);
  const nDays = Math.round((end.getTime() - start.getTime()) / 86400000);

  const dates: string[] = [];
  const precipMm: number[] = [];
  const tmaxC: number[] = [];
  const tminC: number[] = [];
  const tmeanC: number[] = [];
  const petMm: number[] = [];
  const aetMm: number[] = [];
  const soilMoistureMm: number[] = [];
  const dischargeM3s: number[] = [];
  const stageM: number[] = [];

  const gageCodes = ['DEMO-01638500', 'DEMO-01619500', 'DEMO-01643000'];
  const gageAreas = [24996, 2999, 4249];
  const byGage: Record<string, number[]> = Object.fromEntries(gageCodes.map((c) => [c, []]));

  // Conceptual stores, all in mm of depth over the catchment, so the
  // generated series closes P = Q + ET + ΔS exactly by construction.
  let soil = 180;
  let quickStore = 0;
  let slowStore = 60;
  const SOIL_CAP = 330;
  const DEPTH_TO_FLOW = (AREA_KM2 * 1e6) / (1000 * 86400); // mm/d -> m3/s

  for (let i = 0; i < nDays; i++) {
    const d = new Date(start.getTime() + i * 86400000);
    const iso = d.toISOString().slice(0, 10);
    const doy = Math.floor((d.getTime() - Date.UTC(d.getUTCFullYear(), 0, 1)) / 86400000) + 1;

    const seasonal = Math.sin((2 * Math.PI * (doy - 100)) / 365.25);
    // Two superposed multi-year oscillations give realistic drought clustering.
    const decadal = 0.6 * Math.sin((2 * Math.PI * i) / (365.25 * 6.4)) + 0.4 * Math.sin((2 * Math.PI * i) / (365.25 * 11.3) + 1.1);

    // --- Precipitation -----------------------------------------------------
    const pWet = 0.30 + 0.05 * seasonal + 0.055 * decadal;
    let p = 0;
    if (r() < pWet) {
      const u = Math.max(r(), 1e-9);
      p = -Math.log(u) * (9.5 + 2.6 * seasonal + 1.9 * decadal);
      // Occasional frontal / tropical system.
      if (r() < 0.011) p *= 2.6 + 2.2 * r();
    }
    p = Math.max(Number(p.toFixed(2)), 0);

    // --- Temperature -------------------------------------------------------
    const tmean = 12.8 + 12.4 * Math.sin((2 * Math.PI * (doy - 112)) / 365.25) + (r() - 0.5) * 5.2 + 0.012 * (i / 365.25);
    const range = 10.5 + (r() - 0.5) * 4 - (p > 5 ? 3 : 0);
    const tmax = tmean + range / 2;
    const tmin = tmean - range / 2;
    const pet = hargreavesPet(tmax, tmin, LATITUDE, doy);

    // --- Soil moisture and runoff generation --------------------------------
    // Saturation-excess analogue: the fraction of rainfall that runs off
    // directly rises with catchment wetness. Everything else infiltrates, so
    // the balance closes without a fudge term.
    const wetness = soil / SOIL_CAP;
    const runoffCoef = 0.05 + 0.50 * wetness ** 2;
    const direct = p * runoffCoef;
    soil = Math.min(soil + (p - direct), SOIL_CAP);

    const aet = Math.min(pet * (0.20 + 0.80 * (soil / SOIL_CAP)), soil);
    soil -= aet;

    // Drainage to the slow store once the profile is above field capacity.
    const recharge = soil > 0.55 * SOIL_CAP ? (soil - 0.55 * SOIL_CAP) * 0.06 : 0;
    soil = Math.max(soil - recharge, 0);

    // --- Routing: two linear stores, both in mm ----------------------------
    quickStore += direct;
    const qQuick = quickStore * 0.45;
    quickStore -= qQuick;

    slowStore += recharge;
    const qSlow = slowStore * 0.022;
    slowStore -= qSlow;

    const runoffDepth = qQuick + qSlow; // mm/day
    const q = Math.max(runoffDepth * DEPTH_TO_FLOW, 4);
    // Stage from a power-law rating curve, Q = a·hᵇ  ->  h = (Q/a)^(1/b)
    const stage = Number((0.42 * (q / 25) ** 0.42).toFixed(3));

    dates.push(iso);
    precipMm.push(p);
    tmaxC.push(Number(tmax.toFixed(2)));
    tminC.push(Number(tmin.toFixed(2)));
    tmeanC.push(Number(tmean.toFixed(2)));
    petMm.push(Number(pet.toFixed(3)));
    aetMm.push(Number(aet.toFixed(3)));
    soilMoistureMm.push(Number(soil.toFixed(2)));
    dischargeM3s.push(Number(q.toFixed(2)));
    stageM.push(stage);

    // Tributary gauges scale by area with an independent flashiness factor.
    gageCodes.forEach((code, k) => {
      if (k === 0) {
        byGage[code].push(Number(q.toFixed(2)));
        return;
      }
      // Smaller, flashier tributaries: more of the response in the quick
      // store, proportionally less sustained baseflow.
      const areaRatio = gageAreas[k] / AREA_KM2;
      const flashiness = k === 1 ? 1.45 : 1.2;
      const qt = Math.max((qQuick * flashiness + qSlow * 0.75) * DEPTH_TO_FLOW * areaRatio, 0.25);
      byGage[code].push(Number(qt.toFixed(2)));
    });
  }

  return { dates, precipMm, tmaxC, tminC, tmeanC, petMm, aetMm, soilMoistureMm, dischargeM3s, stageM, byGage };
}

/**
 * Water quality sampled roughly monthly at three stations, with realistic
 * dependencies: temperature drives dissolved oxygen; storm flow drives
 * turbidity, TSS and E. coli; agricultural subbasins carry higher nutrients.
 */
function generateWaterQuality(daily: DemoDaily, seed: number): DemoWaterQuality[] {
  const r = rng(seed);
  const out: DemoWaterQuality[] = [];
  const stations = [
    { code: 'DEMO-WQ-POR', nutrientFactor: 1.0, ecoliFactor: 1.0 },
    { code: 'DEMO-WQ-ANT', nutrientFactor: 1.7, ecoliFactor: 2.1 },
    { code: 'DEMO-WQ-MON', nutrientFactor: 2.1, ecoliFactor: 2.6 },
  ];

  const medianQ = [...daily.dischargeM3s].sort((a, b) => a - b)[Math.floor(daily.dischargeM3s.length / 2)];

  for (let i = 0; i < daily.dates.length; i++) {
    // Sample near the middle of each month.
    const day = Number(daily.dates[i].slice(8, 10));
    if (day !== 14) continue;
    const q = daily.dischargeM3s[i];
    const flowRatio = q / medianQ;
    const temp = Math.max(daily.tmeanC[i] * 0.86 + 2.4 + (r() - 0.5) * 1.4, 0.4);

    for (const st of stations) {
      const push = (parameter: string, value: number, unit: string) =>
        out.push({ t: daily.dates[i], stationCode: st.code, parameter, value: Number(value.toFixed(3)), unit });

      // DO saturation falls with temperature (Benson & Krause form, simplified).
      const doSat = 14.652 - 0.41022 * temp + 0.007991 * temp ** 2 - 0.000077774 * temp ** 3;
      push('temperature', temp, 'degC');
      push('dissolved_oxygen', Math.max(doSat * (0.86 + 0.1 * r()) - (st.nutrientFactor - 1) * 0.9, 1.2), 'mg/L');
      push('ph', 7.6 - 0.22 * (st.nutrientFactor - 1) + (r() - 0.5) * 0.5, 'pH');
      push('turbidity', Math.max(3 + 21 * Math.max(flowRatio - 0.9, 0) ** 1.5 + r() * 4, 0.6), 'NTU');
      push('conductivity', 210 + 95 * (st.nutrientFactor - 1) + (r() - 0.5) * 60 - 40 * Math.max(flowRatio - 1, 0), 'uS/cm');
      push('tds', 130 + 62 * (st.nutrientFactor - 1) + (r() - 0.5) * 36, 'mg/L');
      push('nitrate', Math.max(0.9 * st.nutrientFactor + 1.5 * Math.max(flowRatio - 1, 0) * st.nutrientFactor + (r() - 0.5) * 0.6, 0.05), 'mg/L');
      push('phosphate', Math.max(0.035 * st.nutrientFactor + 0.09 * Math.max(flowRatio - 1, 0) * st.nutrientFactor + r() * 0.02, 0.004), 'mg/L');
      push('ammonia', Math.max(0.05 * st.nutrientFactor + r() * 0.05, 0.005), 'mg/L');
      push('chlorophyll_a', Math.max(3.5 * st.nutrientFactor + 9 * Math.max(temp - 18, 0) / 8 + r() * 3, 0.5), 'ug/L');
      push('e_coli', Math.max(28 * st.ecoliFactor * (1 + 5.5 * Math.max(flowRatio - 1, 0)) * (0.6 + r()), 4), 'MPN/100mL');
      push('tss', Math.max(6 + 34 * Math.max(flowRatio - 0.9, 0) ** 1.4 + r() * 5, 1), 'mg/L');
      push('toc', Math.max(2.6 + 2.2 * Math.max(flowRatio - 1, 0) + r() * 0.8, 0.8), 'mg/L');
    }
  }
  return out;
}

/** Monthly reservoir operation: inflow from the catchment, seasonal rule curve. */
function generateReservoir(daily: DemoDaily, seed: number) {
  const r = rng(seed);
  const capacityMcm = 380;
  const deadStorageMcm = 42;
  const conservationPoolMcm = 300;
  const floodPoolMcm = 350;

  // Aggregate daily flow to monthly volume; the reservoir intercepts ~3 %
  // of basin runoff, the share of the catchment draining to the dam.
  const byMonth = new Map<string, { qSum: number; n: number; petSum: number }>();
  for (let i = 0; i < daily.dates.length; i++) {
    const k = daily.dates[i].slice(0, 7);
    const rec = byMonth.get(k) ?? { qSum: 0, n: 0, petSum: 0 };
    rec.qSum += daily.dischargeM3s[i];
    rec.petSum += daily.petMm[i];
    rec.n += 1;
    byMonth.set(k, rec);
  }

  let storage = 268;
  const monthly: DemoReservoirStep[] = [];
  for (const [month, rec] of [...byMonth.entries()].sort()) {
    const days = rec.n;
    const inflowM3s = (rec.qSum / days) * 0.03;
    const inflowMcm = (inflowM3s * days * 86400) / 1e6;
    const evapMcm = (rec.petSum / 1000) * 11.5; // ~11.5 km2 pool area
    const monthNum = Number(month.slice(5, 7));
    // Rule curve: draw down through summer, refill in late winter and spring.
    const target = monthNum >= 4 && monthNum <= 10 ? conservationPoolMcm * 0.82 : conservationPoolMcm;
    const demandRelease = Math.max((storage - target) * 0.25, 0) + 6 + 3 * Math.max(0, Math.sin(((monthNum - 4) / 12) * 2 * Math.PI));
    const release = Math.min(demandRelease * (0.9 + 0.2 * r()), Math.max(storage - deadStorageMcm + inflowMcm - evapMcm, 0));

    storage = storage + inflowMcm - evapMcm - release;
    let spillMcm = 0;
    if (storage > floodPoolMcm) {
      spillMcm = storage - floodPoolMcm;
      storage = floodPoolMcm;
    }
    storage = Math.max(storage, deadStorageMcm);

    const daysInMonth = days;
    monthly.push({
      t: `${month}-01`,
      storageMcm: Number(storage.toFixed(2)),
      // Simple storage–elevation curve.
      elevationM: Number((168 + 34 * (storage / capacityMcm) ** 0.62).toFixed(2)),
      inflowM3s: Number(inflowM3s.toFixed(2)),
      releaseM3s: Number(((release * 1e6) / (daysInMonth * 86400)).toFixed(2)),
      spillM3s: Number(((spillMcm * 1e6) / (daysInMonth * 86400)).toFixed(2)),
      evaporationMcm: Number(evapMcm.toFixed(3)),
    });
  }
  return {
    id: DEMO_IDS.reservoir,
    name: 'Catoctin Demonstration Reservoir',
    lon: -77.47,
    lat: 39.62,
    capacityMcm,
    deadStorageMcm,
    conservationPoolMcm,
    floodPoolMcm,
    purpose: ['water supply', 'flow augmentation', 'flood risk reduction', 'recreation'],
    monthly,
  };
}

/** Monthly demand by sector with population growth and weather sensitivity. */
function generateDemand(daily: DemoDaily, seed: number): DemoDemand[] {
  const r = rng(seed);
  const out: DemoDemand[] = [];
  const byMonth = new Map<string, { t: number[]; p: number[] }>();
  for (let i = 0; i < daily.dates.length; i++) {
    const k = daily.dates[i].slice(0, 7);
    const rec = byMonth.get(k) ?? { t: [], p: [] };
    rec.t.push(daily.tmeanC[i]);
    rec.p.push(daily.precipMm[i]);
    byMonth.set(k, rec);
  }
  const months = [...byMonth.keys()].sort();
  const basePopulation = 512_000;

  months.forEach((month, idx) => {
    const rec = byMonth.get(month)!;
    const tmean = rec.t.reduce((a, b) => a + b, 0) / rec.t.length;
    const pTotal = rec.p.reduce((a, b) => a + b, 0);
    const yearsElapsed = idx / 12;
    const population = Math.round(basePopulation * (1 + 0.0118) ** yearsElapsed);
    const monthNum = Number(month.slice(5, 7));
    const daysInMonth = rec.t.length;

    // Municipal: per-capita base with a summer outdoor-use term and a
    // long-run efficiency improvement.
    const perCapitaLd = 402 * (1 - 0.0062 * yearsElapsed);
    const summerFactor = 1 + 0.021 * Math.max(tmean - 16, 0) - 0.00042 * pTotal;
    const municipal = (population * perCapitaLd * daysInMonth * summerFactor) / 1e9; // MCM
    // Agricultural: irrigation demand concentrated May–September.
    const irrigationSeason = monthNum >= 5 && monthNum <= 9 ? 1 : 0.06;
    const agricultural = irrigationSeason * (9.2 + 0.42 * Math.max(tmean - 18, 0) - 0.014 * pTotal) * (1 + 0.004 * yearsElapsed);
    const industrial = 4.6 * (1 + 0.0071) ** yearsElapsed * (0.94 + 0.12 * r());

    out.push({ t: `${month}-01`, sector: 'municipal', demandMcm: Number(municipal.toFixed(3)), population });
    out.push({ t: `${month}-01`, sector: 'agricultural', demandMcm: Number(Math.max(agricultural, 0.2).toFixed(3)), population });
    out.push({ t: `${month}-01`, sector: 'industrial', demandMcm: Number(industrial.toFixed(3)), population });
  });
  return out;
}

/** Monthly groundwater level responding to recharge with a lag. */
function generateGroundwater(daily: DemoDaily, seed: number) {
  const r = rng(seed);
  const out: { t: string; depthToWaterM: number }[] = [];
  let level = 8.4;
  const byMonth = new Map<string, number>();
  for (let i = 0; i < daily.dates.length; i++) {
    const k = daily.dates[i].slice(0, 7);
    byMonth.set(k, (byMonth.get(k) ?? 0) + daily.precipMm[i] - daily.aetMm[i]);
  }
  for (const [month, netMm] of [...byMonth.entries()].sort()) {
    level = level * 0.86 + 1.4 - netMm * 0.0072 + (r() - 0.5) * 0.18;
    level = Math.min(Math.max(level, 2.1), 17.5);
    out.push({ t: `${month}-01`, depthToWaterM: Number(level.toFixed(2)) });
  }
  return out;
}
